
CREATE CURSOR MiCursor (IdReg C(20))
FOR ln = 1 TO 10
INSERT INTO MiCursor VALUES ("REGISTRO " + TRANSFORM(ln))
ENDFOR

*-- Inserto antes del 5to. registro
GO 5
INSERT BEFORE BLANK
REPLACE IdReg WITH "NUEVO EN POSICION " + TRANSFORM(RECNO())
BROWSE